<?php

/**
 * BaseCustomerAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $email
 * @property string $token
 * @property boolean $is_active
 * @property Doctrine_Collection $CustomerCategoryAffiliate
 * 
 * @method string              getUrl()                       Returns the current record's "url" value
 * @method string              getEmail()                     Returns the current record's "email" value
 * @method string              getToken()                     Returns the current record's "token" value
 * @method boolean             getIs_actIve()                 Returns the current record's "is_active" value
 * @method Doctrine_Collection getCustomerCategoryAffiliate() Returns the current record's "CustomerCategoryAffiliate" collection
 * @method CustomerAffiliate   setUrl()                       Sets the current record's "url" value
 * @method CustomerAffiliate   setEmail()                     Sets the current record's "email" value
 * @method CustomerAffiliate   setToken()                     Sets the current record's "token" value
 * @method CustomerAffiliate   setIs_actIve()                 Sets the current record's "is_active" value
 * @method CustomerAffiliate   setCustomerCategoryAffiliate() Sets the current record's "CustomerCategoryAffiliate" collection
 * 
 * @package    tts_nam
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomerAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer_affiliate');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CustomerCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'affiliate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}