<?php

/**
 * BaseCustomerCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $JobeetJobs
 * @property Doctrine_Collection $CustomerCategoryAffiliate
 * 
 * @method string              getName()                      Returns the current record's "name" value
 * @method Doctrine_Collection getJobeetJobs()                Returns the current record's "JobeetJobs" collection
 * @method Doctrine_Collection getCustomerCategoryAffiliate() Returns the current record's "CustomerCategoryAffiliate" collection
 * @method CustomerCategory    setName()                      Sets the current record's "name" value
 * @method CustomerCategory    setJobeetJobs()                Sets the current record's "JobeetJobs" collection
 * @method CustomerCategory    setCustomerCategoryAffiliate() Sets the current record's "CustomerCategoryAffiliate" collection
 * 
 * @package    tts_nam
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomerCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CustomerJob as JobeetJobs', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('CustomerCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}