<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/07/01 11:39:48

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony_test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
