<?php

/**
 * CustomerCategoryAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerCategoryAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomerCategoryAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomerCategoryAffiliate');
    }
}