<?php

/**
 * CustomerCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomerCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomerCategory');
    }
}