<?php

/**
 * CustomerJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomerJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomerJob');
    }
}