<?php

/**
 * CustomerAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomerAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomerAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomerAffiliate');
    }
}