<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/07/02 03:25:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony_test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
